name: Release

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: release-drafter/release-drafter@v5
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge back to develop
        uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: "main"
          target_branch: "develop"
          commit_message_template: "Merge {source_ref} into {target_branch}"
